// Code generated by hertz generator.

package post

import (
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _listpostsMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _createpostMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _postsMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getpostMw() []app.HandlerFunc {
	// your code...
	return nil
}
